apiVersion: v1
kind: Pod
metadata:
  name: todoapp-pod
  namespace: mateapp
  labels:
    app: todoapp
spec:
  containers:
  - name: todoapp-container
    image: todoapp:local
    imagePullPolicy: Never
    ports:
    - containerPort: 8000
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
